# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Erlang Ecosystem Foundation

name: "Mix SBoM"
description: "Calculates dependencies for Mix and outputs a CycloneDX File"
author: "Erlang Ecosystem Foundation"
branding:
  icon: arrow-up
  color: blue
inputs:
  project-path:
    required: true
    description: "Repo path to the mix.exs file used to detect dependencies. Defaults to mix.exs in the root of the repository."
    default: "${{ github.workspace }}"
  schema:
    required: true
    description: "CycloneDX Schema Version"
    default: "1.6"
  format:
    required: true
    description: "CycloneDX Output Format"
    default: "json"
  reuse-beam:
    required: false
    description: "Use local BEAM installation instead of pre-compiled binaries. Requires Elixir/Erlang to be set up beforehand."
    default: "false"
outputs:
  sbom-path:
    description: "Path to the generated SBoM"
    value: "${{ steps.define_output.outputs.output }}"
runs:
  using: "composite"
  steps:
    - name: "Download SBoM Tool"
      run: |
        if [ "$REUSE_BEAM" = "true" ]; then
          gh release download "$TAG" --repo erlef/mix_sbom --pattern "mix_sbom.escript" --output mix_sbom
        else
          gh release download "$TAG" --repo erlef/mix_sbom --pattern "mix_sbom_${{ runner.os }}_${{ runner.arch }}" --output mix_sbom
        fi
      shell: "bash"
      working-directory: "${{ runner.temp }}"
      env:
        # TODO: Put real version
        TAG: "VERSION"
        GITHUB_TOKEN: ${{ github.token }}
        REUSE_BEAM: "${{ inputs.reuse-beam }}"
    - name: "Verify SBoM Tool Provenance"
      run: >-
        gh attestation verify
        --repo erlef/mix_sbom
        --source-ref "refs/tags/$TAG"
        mix_sbom
      shell: "bash"
      working-directory: "${{ runner.temp }}"
      env:
        # TODO: Put real version
        TAG: "VERSION"
        GITHUB_TOKEN: ${{ github.token }}
    - name: "Make Tool Executable"
      run: "chmod +x mix_sbom"
      shell: "bash"
      working-directory: "${{ runner.temp }}"
    - name: "Define Output Temp File"
      run: |
        OUTPUT_TEMP="$RUNNER_TEMP/$RANDOM.cdx.$FORMAT"
        echo "output=$OUTPUT_TEMP" >> "$GITHUB_OUTPUT"
      shell: "bash"
      env:
        FORMAT: "${{ inputs.format }}"
      id: define_output
    - name: "Generate SBoM"
      id: generate
      run: >-
        "${{ runner.temp }}/mix_sbom"
        --schema="$SCHEMA"
        --format="$FORMAT"
        --output="$OUTPUT_PATH"
        "$PROJECT_PATH"
      shell: "bash"
      env:
        PROJECT_PATH: "${{ inputs.project-path }}"
        SCHEMA: "${{ inputs.schema }}"
        FORMAT: "${{ inputs.format }}"
        OUTPUT_PATH: "${{ steps.define_output.outputs.output }}"
